name: CI test

on:
  push:
    branches:
      - dev
      - main
  pull_request:
    branches:
      - dev
      - main
jobs:
    setup-env:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout code
            uses: actions/checkout@v4
          - name: Set up Python
            uses: actions/setup-python@v5
            with:
              python-version: '3.10'
          - name: Install dependencies
            run: |
              python -m pip install --upgrade pip
              pip install -r requirements.txt
    lint:
        runs-on: ubuntu-latest
        steps:
          - name: Verifier code
            run: |
              python -m pip install --upgrade pip
              pip install ruff
              ruff check .
    test:
        runs-on: ubuntu-latest
        needs: [setup-env, lint]
        steps:
          - name: Run tests
            run: |
              python -m pip install --upgrade pip
              pytest /tests